# Generated by Django 5.1.6 on 2025-03-02 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="land_records",
            fields=[
                (
                    "land_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("area_acres", models.IntegerField()),
                ("crop_type", models.CharField(max_length=511)),
            ],
            options={
                "db_table": "land_records",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="assets",
            fields=[
                (
                    "asset_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=511)),
                ("location", models.CharField(max_length=2047)),
                ("installation_date", models.DateField()),
                ("budget", models.IntegerField()),
            ],
            options={
                "db_table": "assets",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="env_data",
            fields=[
                (
                    "record_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("rainfall", models.IntegerField()),
                ("aqi", models.IntegerField()),
                ("gwl", models.IntegerField()),
                ("date_of_record", models.DateField()),
                ("temperature", models.IntegerField()),
                ("humidity", models.IntegerField()),
                ("wind_speed", models.IntegerField()),
            ],
            options={
                "db_table": "env_data",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="household",
            fields=[
                (
                    "household_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("address", models.CharField(max_length=2047)),
                ("category", models.CharField(max_length=511)),
                ("income", models.IntegerField()),
            ],
            options={
                "db_table": "household",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("role", models.CharField(max_length=511)),
                ("password_user", models.CharField(max_length=511)),
            ],
            options={
                "db_table": "users",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="welfare_schemes",
            fields=[
                (
                    "scheme_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=511)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "welfare_schemes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="citizen",
            fields=[
                (
                    "citizen_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=511)),
                ("gender", models.CharField(max_length=15)),
                ("dob", models.DateField()),
                ("educational_qualification", models.CharField(max_length=511)),
                ("income", models.IntegerField()),
                (
                    "parent_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.citizen",
                    ),
                ),
                (
                    "household_id",
                    models.ForeignKey(
                        db_column="household_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.household",
                    ),
                ),
            ],
            options={
                "db_table": "citizen",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="certificate_application",
            fields=[
                (
                    "application_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("certificate_type", models.CharField(max_length=511)),
                ("status", models.CharField(max_length=511)),
                (
                    "citizen_id",
                    models.ForeignKey(
                        db_column="citizen_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.citizen",
                    ),
                ),
            ],
            options={
                "db_table": "certificate_application",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="census_data",
            fields=[
                (
                    "census_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("event_type", models.CharField(max_length=511)),
                ("event_date", models.DateField()),
                (
                    "citizen_id",
                    models.ForeignKey(
                        db_column="citizen_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.citizen",
                    ),
                ),
                (
                    "household_id",
                    models.ForeignKey(
                        db_column="household_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.household",
                    ),
                ),
            ],
            options={
                "db_table": "census_data",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="panchayat_employees",
            fields=[
                (
                    "employee_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("role", models.CharField(max_length=511)),
                ("department", models.CharField(max_length=511)),
                (
                    "citizen_id",
                    models.ForeignKey(
                        db_column="citizen_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.citizen",
                    ),
                ),
            ],
            options={
                "db_table": "panchayat_employees",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="certificate",
            fields=[
                (
                    "certificate_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("certificate_type", models.CharField(max_length=511)),
                ("issue_date", models.DateField()),
                (
                    "applicant_id",
                    models.ForeignKey(
                        db_column="citizen_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.citizen",
                    ),
                ),
                (
                    "issuing_official",
                    models.ForeignKey(
                        db_column="employee_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.panchayat_employees",
                    ),
                ),
            ],
            options={
                "db_table": "certificate",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="tax",
            fields=[
                (
                    "tax_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=511)),
                ("amount", models.IntegerField()),
                ("due_date", models.DateField()),
                (
                    "paid_status",
                    models.CharField(
                        choices=[("PAID", "Paid"), ("DUE", "Due")], max_length=511
                    ),
                ),
                (
                    "payer_id",
                    models.ForeignKey(
                        db_column="citizen_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.citizen",
                    ),
                ),
            ],
            options={
                "db_table": "tax",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="vaccinations",
            fields=[
                (
                    "vaccination_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("vaccine_type", models.CharField(max_length=511)),
                ("date_administered", models.DateField()),
                (
                    "citizen_id",
                    models.ForeignKey(
                        db_column="citizen_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.citizen",
                    ),
                ),
            ],
            options={
                "db_table": "vaccinations",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="scheme_enrollments",
            fields=[
                (
                    "enrollment_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("enrollment_date", models.DateField()),
                (
                    "citizen_id",
                    models.ForeignKey(
                        db_column="citizen_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.citizen",
                    ),
                ),
                (
                    "scheme_id",
                    models.ForeignKey(
                        db_column="scheme_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.welfare_schemes",
                    ),
                ),
            ],
            options={
                "db_table": "scheme_enrollments",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="benefit_application",
            fields=[
                (
                    "application_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("status", models.CharField(max_length=511)),
                (
                    "citizen_id",
                    models.ForeignKey(
                        db_column="citizen_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.citizen",
                    ),
                ),
                (
                    "scheme_id",
                    models.ForeignKey(
                        db_column="scheme_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.welfare_schemes",
                    ),
                ),
            ],
            options={
                "db_table": "benefit_application",
                "managed": True,
            },
        ),
    ]
