# Generated by Django 4.2.11 on 2025-02-26 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="household",
            fields=[
                (
                    "household_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("address", models.CharField(max_length=2047)),
                ("income", models.IntegerField()),
            ],
            options={
                "db_table": "household",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="citizen",
            fields=[
                (
                    "citizen_id",
                    models.CharField(max_length=511, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=511)),
                ("gender", models.CharField(max_length=15)),
                ("dob", models.DateField()),
                ("educational_qualification", models.CharField(max_length=511)),
                (
                    "household",
                    models.ForeignKey(
                        db_column="household_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.household",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.citizen",
                    ),
                ),
            ],
            options={
                "db_table": "citizen",
                "managed": True,
            },
        ),
    ]
