# Generated by Django 5.1.6 on 2025-02-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='educational_qualification',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '10th Pass'), (2, '12th Pass'), (3, 'UG'), (4, 'PG'), (5, 'School Going'), (6, 'PhD'), (7, 'Illiterate')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='gender',
            field=models.CharField(default=1988, max_length=1023),
            preserve_default=False,
        ),
    ]
