# Generated by Django 5.1.6 on 2025-02-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_citizen_educational_qualification_citizen_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='household',
            fields=[
                ('household_id', models.CharField(max_length=511, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=2047)),
                ('income', models.IntegerField()),
            ],
            options={
                'db_table': 'household',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='citizen',
            options={'managed': False},
        ),
    ]
