# Generated by Django 5.1.6 on 2025-02-27 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_citizen_citizen_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate_application',
            old_name='applicant_id',
            new_name='citizen_id',
        ),
        migrations.AlterField(
            model_name='citizen',
            name='citizen_id',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.users'),
        ),
        migrations.AlterField(
            model_name='panchayat_employees',
            name='employee_id',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.users'),
        ),
    ]
