# Generated by Django 5.1.6 on 2025-02-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_household_alter_citizen_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizen',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='household',
            options={'managed': True},
        ),
    ]
